<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Laravel Easy Dev Configuration
    |--------------------------------------------------------------------------
    |
    | This file contains the configuration options for Laravel Easy Dev package.
    | You can customize paths, templates, and default behaviors.
    |
    */

    /*
    |--------------------------------------------------------------------------
    | Model Namespace
    |--------------------------------------------------------------------------
    |
    | The default namespace where your models are located. This is used
    | by the commands to correctly qualify model class names.
    |
    */
    'model_namespace' => 'App\\Models\\',

    /*
    |--------------------------------------------------------------------------
    | File Generation Paths
    |--------------------------------------------------------------------------
    |
    | Define the default output directories for files generated by Easy Dev.
    | You can customize these paths to match your project structure.
    |
    */
    'paths' => [
        'models' => app_path('Models'),
        'controllers' => app_path('Http/Controllers'),
        'api_controllers' => app_path('Http/Controllers/Api'),
        'requests' => app_path('Http/Requests'),
        'repositories' => app_path('Repositories'),
        'repository_contracts' => app_path('Repositories/Contracts'),
        'services' => app_path('Services'),
        'service_contracts' => app_path('Services/Contracts'),
        'tests' => base_path('tests'),
        'feature_tests' => base_path('tests/Feature'),
        'unit_tests' => base_path('tests/Unit'),
        'factories' => database_path('factories'),
        'seeders' => database_path('seeders'),
        'migrations' => database_path('migrations'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Route Configuration
    |--------------------------------------------------------------------------
    |
    | Configure how routes should be generated for CRUD operations.
    |
    */
    'routes' => [
        'api_prefix' => 'api',
        'web_prefix' => '',
        'web_middleware' => ['web'],
        'api_middleware' => ['api'],
        'route_model_binding' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Template Configuration
    |--------------------------------------------------------------------------
    |
    | Configure which stub templates to use for file generation.
    | You can publish stubs and customize them as needed.
    |
    */
    'stubs' => [
        'model' => 'model.enhanced',
        'controller' => 'controller.enhanced',
        'api_controller' => 'controller.api.enhanced',
        'repository' => 'repository.enhanced',
        'repository_interface' => 'repository.interface.enhanced',
        'service' => 'service.enhanced',
        'service_interface' => 'service.interface.enhanced',
        'request' => 'request.enhanced',
        'test' => 'test.enhanced',
    ],

    /*
    |--------------------------------------------------------------------------
    | Default Command Options
    |--------------------------------------------------------------------------
    |
    | Set default options for commands. Users can still override these
    | with command-line flags.
    |
    */
    'defaults' => [
        'with_repository' => false,
        'with_service' => false,
        'with_interface' => true,
        'generate_api_controller' => true,
        'generate_web_controller' => true,
        'generate_tests' => false,
        'generate_factory' => false,
        'generate_seeder' => false,
    ],

    /*
    |--------------------------------------------------------------------------
    | Validation Rules Configuration
    |--------------------------------------------------------------------------
    |
    | Configure how validation rules are generated based on field types.
    |
    */
    'validation' => [
        'rules' => [
            'string' => 'required|string|max:255',
            'text' => 'required|string',
            'integer' => 'required|integer',
            'bigInteger' => 'required|integer',
            'decimal' => 'required|numeric',
            'float' => 'required|numeric',
            'boolean' => 'required|boolean',
            'date' => 'required|date',
            'datetime' => 'required|date',
            'timestamp' => 'required|date',
            'email' => 'required|email|max:255',
            'password' => 'required|string|min:8',
            'url' => 'required|url|max:255',
            'json' => 'required|json',
            'uuid' => 'required|uuid',
        ],
        
        'field_patterns' => [
            'email' => 'required|email|max:255',
            'password' => 'required|string|min:8',
            'url' => 'required|url|max:255',
            'phone' => 'required|string|max:20',
            'slug' => 'required|string|max:255|unique:{table}',
            'price' => 'required|numeric|min:0',
            'quantity' => 'required|integer|min:0',
            'is_' => 'required|boolean',
            'has_' => 'required|boolean',
            '_id' => 'required|integer|exists:{table},id',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Relationship Detection
    |--------------------------------------------------------------------------
    |
    | Configure how relationships are detected and generated.
    |
    */
    'relationships' => [
        'auto_detect' => true,
        'detect_polymorphic' => true,
        'generate_reverse_relationships' => true,
        'foreign_key_suffix' => '_id',
        'polymorphic_suffix' => '_type',
    ],

    /*
    |--------------------------------------------------------------------------
    | UI Configuration
    |--------------------------------------------------------------------------
    |
    | Configure the command-line interface appearance and behavior.
    |
    */
    'ui' => [
        'show_progress_bar' => true,
        'show_banner' => true,
        'use_icons' => true,
        'colored_output' => true,
        'interactive_mode_default' => false,
    ],

    /*
    |--------------------------------------------------------------------------
    | Database Configuration
    |--------------------------------------------------------------------------
    |
    | Configure database analysis and migration parsing.
    |
    */
    'database' => [
        'analyze_constraints' => true,
        'analyze_indexes' => true,
        'parse_migrations' => true,
        'supported_drivers' => ['mysql', 'pgsql', 'sqlite'],
    ],
];
